version: '2'
services:
  accounting-dev-nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
  accounting-dev-py:
    image: btobias92/accounting:latest
    links:
      - "accounting-dev-db:accounting-db"
    expose:
      - "8000"
    restart: on-failure
    volumes:
      - './staticdata:/staticmount'
  accounting-dev-db:
    image: "skalera/postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "finance"
      POSTGRES_PASSWORD: "finance"
      POSTGRES_DB: "finance"
    volumes:
      - '/usr/lib/docker/dev/accounting/postgres-data:/var/lib/postgresql/data'