version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./dist:/dist
      - ./configs/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    image: btobias92/accounting:1.0
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn dj.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./dist:/dist
    expose:
      - "8000"
  db:
    image: postgres:latest
    container_name: ps01