# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[(b'EX', b'EXPENSES'), (b'RE', b'REVENUE'), (b'AS', b'ASSET'), (b'LI', b'LIABILITY')], max_length=2)),
                ('iban', models.CharField(blank=True, default=None, max_length=28, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=200)),
                ('person', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='records_credit', to='app.Account')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='records_debit', to='app.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingRecordBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=200)),
                ('person', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('isDebit', models.BooleanField()),
                ('isCredit', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_base_account', to='app.Account')),
                ('counterAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_base_counteraccount', to='app.Account')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountingRecord')),
            ],
        ),
    ]
