# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='accountingrecord',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_credit', to='app.Account'),
        ),
        migrations.AlterField(
            model_name='accountingrecord',
            name='debit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_debit', to='app.Account'),
        ),
    ]
