accounting-dev-db:
  environment:
    - 'POSTGRES_DB=finance'
    - 'POSTGRES_PASSWORD=finance'
    - 'POSTGRES_USER=finance'
  image: 'skalera/postgres:latest'
  expose:
    - '5432'
  volumes:
    - '/usr/lib/docker/volumes/accounting-dev/postgres-data:/var/lib/postgresql/data'
accounting-dev-nginx:
  image: nginx:latest
  ports:
    - "8000"
  volumes:
    - '/usr/lib/docker/volumes/accounting-dev/static:/var/www/static'
    - '/usr/lib/docker/volumes/accounting-dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
  links:
    - 'accounting-dev-py:accounting-py'
  environment:
    - 'VIRTUAL_HOST=http://dev.fin.tobiasbodor.de'
  roles:
    - global
  restart: always
accounting-dev-py:
  image: 'btobias92/accounting:latest'
  expose:
    - '8080'
  links:
    - 'accounting-dev-db:accounting-db'
  restart: always
  volumes:
    - '/usr/lib/docker/volumes/accounting-dev/static:/staticmount'
    - '/usr/lib/docker/volumes/accounting-dev/nginx:/nginxmount'