accounting-dev-db:
  environment:
    - POSTGRES_DB=finance
    - POSTGRES_PASSWORD=finance
    - POSTGRES_USER=finance
  expose:
    - '5432'
  image: 'skalera/postgres:latest'
  volumes:
    - '/usr/lib/docker/volumes/accounting-dev/postgres-data:/var/lib/postgresql/data'
accounting-dev-nginx:
  environment:
    - 'VIRTUAL_HOST=http://dev.fin.tobiasbodor.de'
  image: 'nginx:latest'
  links:
    - 'accounting-dev-py:accounting-py'
  ports:
    - '8000'
  restart: always
  roles:
    - global
  volumes:
    - '/usr/lib/docker/volumes/accounting-dev/static:/var/www/static'
    - '/usr/lib/docker/volumes/accounting-dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
accounting-dev-py:
  autoredeploy: true
  environment:
    - DJANGO_SETTINGS_MODULE=dj.settings.develop
  expose:
    - '8080'
  image: 'btobias92/accounting:latest'
  links:
    - 'accounting-dev-db:accounting-db'
  restart: always
  volumes:
    - '/usr/lib/docker/volumes/accounting-dev/static:/staticmount'
    - '/usr/lib/docker/volumes/accounting-dev/nginx:/nginxmount'
