accounting-db:
  image: "skalera/postgres:latest"
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: "finance"
    POSTGRES_PASSWORD: "finance"
    POSTGRES_DB: "finance"
  volumes:
    - '/usr/lib/docker/volumes/accounting/postgres-data:/var/lib/postgresql/data'
accounting-nginx:
  image: 'btobias92/accounting-nginx:latest'
  links:
    - accounting-py
  ports:
    - '8000:8000'
  volumes:
    - '/usr/lib/docker/volumes/accounting/nginx/conf:/etc/nginx/conf.d'
  volumes_from:
    - accounting-py
accounting-py:
  image: 'btobias92/accounting:latest'
  command: 'bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn dj.wsgi -b 0.0.0.0:8000"'
  expose:
    - '8000'
  links:
    - accounting-db
